# Continuous integration with travis
language: r
sudo: required


# cache packages to speed up builds
cache: packages

before_install:
  sudo apt-get install texinfo

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      
r_binary_packages:
- rgdal

r_packages:
 - curl
 - raster 
 - sp
 - xml2
 - grid 
 - gridExtra
 - httr
 - dplyr
 - stringi
 - tidyr
 - covr
 - devtools



after_success:
 - Rscript -e 'library(covr);codecov()'

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel







